services:
  db:
    container_name: postgres-mv
    image: postgres:15
    environment:
      POSTGRES_USER: codeNaren
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: