CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT name_unique UNIQUE (name);

CREATE TABLE customers_roles
(
    customer_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    CONSTRAINT pk_customers_roles PRIMARY KEY (customer_id, role_id)
);

ALTER TABLE customers_roles
    ADD CONSTRAINT fk_customer_role_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE customers_roles
    ADD CONSTRAINT fk_customer_role_idPkZBqh FOREIGN KEY (role_id) REFERENCES role (id);